matrix:
  include:
    - language: python
      name: "PEP8 check (Python 3.6)"
      python: 3.6
      os: linux
      fail_fast: true
      env:
        - SKIP_INTERPRETER=true
      before_install:
        - git clone https://github.com/TravisToolbox/pycodestyle-travis.git
        - mv requirements.txt req.txt
        - touch requirements.txt
      install:
        - ./pycodestyle-travis/install.sh
      script:
        - ./pycodestyle-travis/scan.sh
