# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

env:
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: 123456

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs: 
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: l2        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: 123456
        ports:
          - 5432:5432

      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements-tests.txt
    - name: Testing
      run: |
        python manage.py test
